[Rainmeter]

[Variables]

[DisabledApp]
ImageAlpha=75
FontColor=#SuperColor#,75
MouseOverAction=[]
MouseLeaveAction=[]
FillColor=Fill Color #SuperColor#,75

;---

[1]
MeterStyle=InfoStyle | DisabledApp

[1Icon]
MeterStyle=IconStyle | DisabledApp

[1Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[2]
MeterStyle=InfoStyle | DisabledApp

[2Icon]
MeterStyle=IconStyle | DisabledApp

[2Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[6]
MeterStyle=InfoStyle | DisabledApp

[6Icon]
MeterStyle=IconStyle | DisabledApp

[6Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[9]
MeterStyle=InfoStyle | DisabledApp

[9Icon]
MeterStyle=IconStyle | DisabledApp

[9Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[13]
MeterStyle=InfoStyle | DisabledApp

[13Icon]
MeterStyle=IconStyle | DisabledApp

[13Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[14]
MeterStyle=InfoStyle | DisabledApp

[14Icon]
MeterStyle=IconStyle | DisabledApp

[14Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[16]
MeterStyle=InfoStyle | DisabledApp

[16Icon]
MeterStyle=IconStyle | DisabledApp

[16Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[17]
MeterStyle=InfoStyle | DisabledApp

[17Icon]
MeterStyle=IconStyle | DisabledApp

[17Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---

[18]
MeterStyle=InfoStyle | DisabledApp

[18Icon]
MeterStyle=IconStyle | DisabledApp

[18Arrow]
MeterStyle=ArrowStyle | DisabledApp

;---