chcp 1252

@echo off

set gamesfol1="Giochi per Browser"
set gamesfol2="Campagna"
set gamesfol3="Casual"
set gamesfol4="Indie"
set gamesfol5="Multiplayer Locali"
set gamesfol6="Multiplayer Online"
set gamesfol7="Simulazione"
set gamesfol8="Sport & Corse"
set gamesfol9="Realtà Virtuale"
set gamescamfol1="Azione"
set gamescamfol2="Horror"
set gamescamfol3="Rilassanti"
set gamescamfol4="RPG"
set gamescamfol5="Sopravvivenza"
set gameslocfol1="Co-op"
set gameslocfol2="Party"
set gameslocfol3="Versus"
set gamesonlfol1="Battle Royale"
set gamesonlfol2="MMO"
set gamesonlfol3="Sparatutto"
set gamesonlfol4="Strategia"

set newsmediafol1="Estremo Sinistro"
set newsmediafol2="Estremo Destro"
set newsmediafol3="Internazionale"

set onlinetools1fol="Diagnostica"

set podcastsfol1="Crime & Dramma"
set podcastsfol2="Politica"
set podcastsfol3="Scienza & Tecnologia"
set podcastsfol4="Sex & Psicologia"
set podcastsfol5="Sport"
set podcastsfol6="Talk Show"

set bookmarksfol1="Notizie & Media"
set bookmarksfol2="Strumenti Online"
set bookmarksfol3="Podcast"
set bookmarksfol4="Shopping"
set bookmarks1="Facebook"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Hulu"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Prompt dei Comandi"
set advanced2="Gestore Dispositivii"
set advanced3="Pulizia del Disco"
set advanced4="Gestore dei Dischi"
set advanced5="Editor dei Registry"
set advanced6="Monitor delle Risorse"
set advanced7="App all'Avvio"
set advanced8="Spazi di Archiviazione"
set advanced9="Configurazione di Sistema"
set advanced10="Firewall di Windows"
set advanced11="Powershell di Windows"
set advanced12="Servizi di Windows"

set controlfol1="Controlli avannzati"
set control1="Sfondi Desktop"
set control2="Ipostazioni Display"
set control3="Ingrandisci"
set control4="Tastiera sullo schermo"
set control5="Opzioni di alimentazione"
set control6="Cestino"
set control7="Cambia display"
set control8="Informazioni di Sistema"
set control9="Task Manager"
set control10="Disinstalla un programma"
set control11="Account Utente"

set advancedseven1="Prompt dei Comandi"
set advancedseven2="Gestore Dispositivii"
set advancedseven3="Pulizia del Disco"
set advancedseven4="Gestore dei Dischi"
set advancedseven5="Editor dei Registry"
set advancedseven6="Monitor delle Risorse"
set advancedseven7="Spazi di Archiviazione"
set advancedseven8="Configurazione di Sistema"
set advancedseven9="Firewall di Windows"
set advancedseven10="Powershell di Windows"
set advancedseven11="Servizi di Windows"

set controlsevenfol1="Controlli avannzati"
set controlseven1="Sfondi Desktop"
set controlseven2="Ipostazioni Display"
set controlseven3="Ingrandisci"
set controlseven4="Tastiera sullo schermo"
set controlseven5="Opzioni di alimentazione"
set controlseven6="Cestino"
set controlseven7="Cambia display"
set controlseven8="Informazioni di Sistema"
set controlseven9="Disinstalla un programma"
set controlseven10="Account Utente"

cd %~dp0

call "RenameShortcuts.bat"