chcp 932

@echo off

set gamesfol1="ブラウザゲーム"
set gamesfol2="キャンペーン"
set gamesfol3="カジュアル"
set gamesfol4="インディーズ"
set gamesfol5="ローカルマルチプレイ"
set gamesfol6="オンラインマルチプレイヤー"
set gamesfol7="シミュレーション"
set gamesfol8="スポーツ＆レーシング"
set gamesfol9="バーチャルリアリティ"
set gamescamfol1="アクション"
set gamescamfol2="ホラー"
set gamescamfol3="リラックス"
set gamescamfol4="RPG"
set gamescamfol5="サバイバル"
set gameslocfol1="Co-op"
set gameslocfol2="パーティー"
set gameslocfol3="対戦"
set gamesonlfol1="大乱戦"
set gamesonlfol2="MMO"
set gamesonlfol3="シューティングゲーム"
set gamesonlfol4="戦略ゲーム"

set newsmediafol1="左端"
set newsmediafol2="右端"
set newsmediafol3="インターナショナル"

set onlinetools1fol="診断"

set podcastsfol1="犯罪ドラマ"
set podcastsfol2="政治"
set podcastsfol3="科学技術"
set podcastsfol4="セックス＆心理学"
set podcastsfol5="スポーツ"
set podcastsfol6="トークショー"

set bookmarksfol1="ニュース＆メディア"
set bookmarksfol2="オンラインツール"
set bookmarksfol3="ポッドキャスト"
set bookmarksfol4="ショッピング"
set bookmarks1="Facebook"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Hulu"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="コマンド・プロンプト"
set advanced2="デバイスマネージャ"
set advanced3="ディスククリーンアップ"
set advanced4="ディスクの管理"
set advanced5="レジストリエディタ"
set advanced6="リソースモニタ"
set advanced7="スタートアップのアプリ"
set advanced8="記憶域"
set advanced9="システム構成"
set advanced10="Windowsファイアウォール"
set advanced11="Windows PowerShell"
set advanced12="Windowsサービス"

set controlfol1="高度なコントロール"
set control1="デスクトップの背景"
set control2="ディスプレイの設定"
set control3="拡大鏡"
set control4="オンスクリーンキーボード"
set control5="電源オプション"
set control6="ごみ箱"
set control7="セカンドディスプレイの設定"
set control8="システム情報"
set control9="タスクマネージャー"
set control10="プログラムのアンインストール"
set control11="ユーザーアカウント"

set advancedseven1="コマンド・プロンプト"
set advancedseven2="デバイスマネージャ"
set advancedseven3="ディスククリーンアップ"
set advancedseven4="ディスクの管理"
set advancedseven5="レジストリエディタ"
set advancedseven6="リソースモニタ"
set advancedseven7="記憶域"
set advancedseven8="システム構成"
set advancedseven9="Windowsファイアウォール"
set advancedseven10="Windows PowerShell"
set advancedseven11="Windowsサービス"

set controlsevenfol1="高度なコントロール"
set controlseven1="デスクトップの背景"
set controlseven2="ディスプレイの設定"
set controlseven3="拡大鏡"
set controlseven4="オンスクリーンキーボード"
set controlseven5="電源オプション"
set controlseven6="ごみ箱"
set controlseven7="セカンドディスプレイの設定"
set controlseven8="システム情報"
set controlseven9="プログラムのアンインストール"
set controlseven10="ユーザーアカウント"

cd %~dp0

call "RenameShortcuts.bat"