chcp 437

@echo off

set gamesfol1="Browser games"
set gamesfol2="Een speler"
set gamesfol3="Gewoontjes"
set gamesfol4="Onafhankelijk"
set gamesfol5="Lokale multiplayer"
set gamesfol6="Online multiplayer"
set gamesfol7="Simulatie"
set gamesfol8="Sport en racen"
set gamesfol9="Virtuele realiteit"
set gamescamfol1="Actie"
set gamescamfol2="Verschrikking"
set gamescamfol3="Ontspannen"
set gamescamfol4="RPG"
set gamescamfol5="Overleving"
set gameslocfol1="Coöperatief"
set gameslocfol2="Partij"
set gameslocfol3="Versus"
set gamesonlfol1="Vecht tegen koninklijk"
set gamesonlfol2="MMO"
set gamesonlfol3="Schutter"
set gamesonlfol4="Strategie"

set newsmediafol1="Far-Left"
set newsmediafol2="Far-Right"
set newsmediafol3="Internationale"

set onlinetools1fol="Diagnostiek"

set podcastsfol1="Misdaad & Drama"
set podcastsfol2="Politiek"
set podcastsfol3="Wetenschap & Technologie"
set podcastsfol4="Seks & Psychologie"
set podcastsfol5="Sport"
set podcastsfol6="Talk shows"

set bookmarksfol1="Nieuws en media"
set bookmarksfol2="Online tools"
set bookmarksfol3="Podcasts"
set bookmarksfol4="Shopping"
set bookmarks1="Facebook"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Hulu"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Commandoprompt"
set advanced2="Apparaatbeheer"
set advanced3="Schijf schoonmaak"
set advanced4="Schijfbeheer"
set advanced5="Registry beheer"
set advanced6="Bronnenmonitor"
set advanced7="Opstart-apps"
set advanced8="Opslagruimtes"
set advanced9="Systeemconfiguratie"
set advanced10="Windows firewall"
set advanced11="Windows PowerShell"
set advanced12="Windows services"

set controlfol1="Geavanceerde opties"
set control1="Bureaublad achtergrond"
set control2="Display instellingen"
set control3="Inzoomen"
set control4="Scherm-toetsenbord"
set control5="Energieopties"
set control6="Prullenbak"
set control7="Wissel scherm"
set control8="Systeem informatie"
set control9="Taak beheer"
set control10="Programma verwijderen"
set control11="Gebruikers accounts"

set advancedseven1="Commandoprompt"
set advancedseven2="Apparaatbeheer"
set advancedseven3="Schijf schoonmaak"
set advancedseven4="Schijfbeheer"
set advancedseven5="Registry beheer"
set advancedseven6="Bronnenmonitor"
set advancedseven7="Opslagruimtes"
set advancedseven8="Systeemconfiguratie"
set advancedseven9="Windows firewall"
set advancedseven10="Windows PowerShell"
set advancedseven11="Windows services"

set controlsevenfol1="Geavanceerde opties"
set controlseven1="Bureaublad achtergrond"
set controlseven2="Display instellingen"
set controlseven3="Inzoomen"
set controlseven4="Scherm-toetsenbord"
set controlseven5="Energieopties"
set controlseven6="Prullenbak"
set controlseven7="Wissel scherm"
set controlseven8="Systeem informatie"
set controlseven9="Programma verwijderen"
set controlseven10="Gebruikers accounts"

cd %~dp0

call "RenameShortcuts.bat"