chcp 1250

@echo off

set gamesfol1="Gry w przegl¹darce"
set gamesfol2="Kampania"
set gamesfol3="Rekreacyjne"
set gamesfol4="Niezale¿ne"
set gamesfol5="Local multiplayer"
set gamesfol6="Online multiplayer"
set gamesfol7="Symulacje"
set gamesfol8="Sportowe i wyœcigowe"
set gamesfol9="Wirtualna rzeczywistoœæ"
set gamescamfol1="Akcja"
set gamescamfol2="Horror"
set gamescamfol3="Spokojne"
set gamescamfol4="RPG"
set gamescamfol5="Surwiwal"
set gameslocfol1="Kooperacja"
set gameslocfol2="Impreza"
set gameslocfol3="Versus"
set gamesonlfol1="Battle Royale"
set gamesonlfol2="MMO"
set gamesonlfol3="Strzelanki"
set gamesonlfol4="Strategie"

set newsmediafol1="Skrajnie lewicowe"
set newsmediafol2="Skrajnie prawicowe"
set newsmediafol3="Miêdzynarodowe"

set onlinetools1fol="Diagnostyka"

set podcastsfol1="Kryminalne i obyczajowe"
set podcastsfol2="Polityka"
set podcastsfol3="Nauka i Technologia"
set podcastsfol4="Seks i Psychologia"
set podcastsfol5="Sport"
set podcastsfol6="Wywiady"

set bookmarksfol1="Wiadomoœci i media"
set bookmarksfol2="Narzêdzia internetowe"
set bookmarksfol3="Podcasty"
set bookmarksfol4="Zakupy"
set bookmarks1="Facebook"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Hulu"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Wiersz poleceñ"
set advanced2="Menad¿er urz¹dzeñ"
set advanced3="Czyszczenie dysku"
set advanced4="Zarz¹dzanie dyskami"
set advanced5="Edytor rejestru"
set advanced6="Monitor zasobów"
set advanced7="Autostart"
set advanced8="Miejsce na dyskach"
set advanced9="Konfiguracja systemu"
set advanced10="Firewall Windows"
set advanced11="Windows PowerShell"
set advanced12="Us³ugi Windows"

set controlfol1="Ustawienia zaawansowane"
set control1="T³o pulpitu"
set control2="Ustawienia wyœwietlania"
set control3="Powiêkszenie"
set control4="Klawiatura ekranowa"
set control5="Opcje zasilania"
set control6="Kosz"
set control7="Prze³¹cz ekran"
set control8="Informacje systemowe"
set control9="Menad¿er zadañ"
set control10="Odinstaluj program"
set control11="Zarz¹dzanie kontami"

set advancedseven1="Wiersz poleceñ"
set advancedseven2="Menad¿er urz¹dzeñ"
set advancedseven3="Czyszczenie dysku"
set advancedseven4="Zarz¹dzanie dyskami"
set advancedseven5="Edytor rejestru"
set advancedseven6="Monitor zasobów"
set advancedseven7="Miejsce na dyskach"
set advancedseven8="Konfiguracja systemu"
set advancedseven9="Firewall Windows"
set advancedseven10="Windows PowerShell"
set advancedseven11="Us³ugi Windows"

set controlsevenfol1="Ustawienia zaawansowane"
set controlseven1="T³o pulpitu"
set controlseven2="Ekran"
set controlseven3="Powiêkszenie"
set controlseven4="Klawiatura ekranowa"
set controlseven5="Opcje zasilania"
set controlseven6="Kosz"
set controlseven7="Prze³¹cz ekran"
set controlseven8="Informacje systemowe"
set controlseven9="Odinstaluj program"
set controlseven10="Konta u¿ytkowników"

cd %~dp0

call "RenameShortcuts.bat"