chcp 1250

@echo off

set gamesfol1="Browser games"
set gamesfol2="Campaign"
set gamesfol3="Casual"
set gamesfol4="Indie"
set gamesfol5="Local multiplayer"
set gamesfol6="Online multiplayer"
set gamesfol7="Simulation"
set gamesfol8="Sports & racing"
set gamesfol9="Virtual Reality"
set gamescamfol1="Action"
set gamescamfol2="Horror"
set gamescamfol3="Relaxed"
set gamescamfol4="RPG"
set gamescamfol5="Survival"
set gameslocfol1="Co-op"
set gameslocfol2="Party"
set gameslocfol3="Versus"
set gamesonlfol1="Battle Royale"
set gamesonlfol2="MMO"
set gamesonlfol3="Shooter"
set gamesonlfol4="Strategy"

set newsmediafol1="V¾avo"
set newsmediafol2="Vpravo"
set newsmediafol3="Medzinárodnı"

set onlinetools1fol="Diaknostika"

set podcastsfol1="Krimi & dráma"
set podcastsfol2="Politika"
set podcastsfol3="Veda a technológia"
set podcastsfol4="Sex & psychológia"
set podcastsfol5="Športy"
set podcastsfol6="Diskusné relácie"

set bookmarksfol1="Správy & média"
set bookmarksfol2="Online nástroje"
set bookmarksfol3="Podkasty"
set bookmarksfol4="Nakupovanie"
set bookmarks1="Facebook"
set bookmarks2="Gmail"
set bookmarks3="Google Keep"
set bookmarks4="Google Maps"
set bookmarks5="Google Photos"
set bookmarks6="Hulu"
set bookmarks7="Netflix"
set bookmarks8="Reddit"
set bookmarks9="Steam"
set bookmarks10="Twitch"
set bookmarks11="YouTube"

set advanced1="Príkazovı riadok"
set advanced2="Správca zariadení"
set advanced3="Èistenie disku"
set advanced4="Správa diskov"
set advanced5="Registry editor"
set advanced6="Resource monitor"
set advanced7="Aplikácie pri spustení"
set advanced8="Ukladacie priestory"
set advanced9="System configuration"
set advanced10="Windows firewall"
set advanced11="Windows PowerShell"
set advanced12="Sluby"

set controlfol1="Nástoje na správu"
set control1="Pozadie"
set control2="Nastavenie obrazovky"
set control3="Zväèšovacie sklo"
set control4="Klávesnica na obrazovke"
set control5="Monosti napájania"
set control6="Kôš"
set control7="Premieta"
set control8="Systémové informácie"
set control9="Správca úloh"
set control10="Aplikácie a súèasti"
set control11="Spravova kontá"

set advancedseven1="Príkazovı riadok"
set advancedseven2="Správca zariadení"
set advancedseven3="Èistenie disku"
set advancedseven4="Správa diskov"
set advancedseven5="Registry editor"
set advancedseven6="Resource monitor"
set advancedseven7="Ukladacie priestory"
set advancedseven8="System configuration"
set advancedseven9="Windows firewall"
set advancedseven10="Windows PowerShell"
set advancedseven11="Sluby"

set controlsevenfol1="Nástoje na správu"
set controlseven1="Pozadie"
set controlseven2="Nastavenie obrazovky"
set controlseven3="Zväèšovacie sklo"
set controlseven4="Klávesnica na obrazovke"
set controlseven5="Monosti napájania"
set controlseven6="Kôš"
set controlseven7="Premieta"
set controlseven8="Systémové informácie"
set controlseven9="Aplikácie a súèasti"
set controlseven10="Spravova kontá"

cd %~dp0

call "RenameShortcuts.bat"