[Variables]

DevicesNumber=2

Devices=Arctis Pro Wireless|44643149312662|Bluetooth#Bluetoothc8:5e:a9:64:1d:1e-28:9a:4b:0e:72:96|0|1|0|Audio/Video|Audio Video Wearable Headset|0|0|0;MX Master 2S|223463262609938|BluetoothLE#BluetoothLEc8:5e:a9:64:1d:1e-cb:3d:18:63:62:12|1|1|0|HumanInterfaceDevice|Mouse|1|90|1;

BTStatus=1

PageDevice1=1
PageDevice2=2
PageDevice3=3
PageDevice4=4
PageDevice5=5
PageDevice6=6
PageDevice7=7
PageDevice8=8

Device1Name=Arctis Pro Wireless
Device2Name=MX Master 2S
Device3Name=MX Master 2S
Device4Name=Surface Arc Mouse
Device5Name=NVIDIA SHIELD Remote
Device6Name=MX Master 2S
Device7Name=NVIDIA SHIELD Remote
Device8Name=NVIDIA SHIELD Remote

Device1Address=44643149312662
Device2Address=223463262609938
Device3Address=223463262609937
Device4Address=254394102878146
Device5Address=79921510527776
Device6Address=223463262609937
Device7Address=79921510527776
Device8Address=79921510527776

Device1Id=Bluetooth#Bluetoothc8:5e:a9:64:1d:1e-28:9a:4b:0e:72:96
Device2Id=BluetoothLE#BluetoothLEc8:5e:a9:64:1d:1e-cb:3d:18:63:62:12
Device3Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-cb:3d:18:63:62:11
Device4Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-e7:5e:be:22:8f:c2
Device5Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20
Device6Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-cb:3d:18:63:62:11
Device7Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20
Device8Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20

Device1Connected=0
Device2Connected=1
Device3Connected=0
Device4Connected=0
Device5Connected=0
Device6Connected=0
Device7Connected=0
Device8Connected=0

Device1Paired=1
Device2Paired=1
Device3Paired=1
Device4Paired=1
Device5Paired=1
Device6Paired=1
Device7Paired=1
Device8Paired=1

Device1CanPair=0
Device2CanPair=0
Device3CanPair=0
Device4CanPair=0
Device5CanPair=0
Device6CanPair=0
Device7CanPair=0
Device8CanPair=0

Device1MajorCategory=Audio/Video
Device2MajorCategory=HumanInterfaceDevice
Device3MajorCategory=HumanInterfaceDevice
Device4MajorCategory=HumanInterfaceDevice
Device5MajorCategory=RemoteControl
Device6MajorCategory=HumanInterfaceDevice
Device7MajorCategory=RemoteControl
Device8MajorCategory=RemoteControl

Device1MinorCategory=Audio Video Wearable Headset
Device2MinorCategory=Mouse
Device3MinorCategory=Mouse
Device4MinorCategory=Mouse
Device5MinorCategory=Unknown
Device6MinorCategory=Mouse
Device7MinorCategory=Unknown
Device8MinorCategory=Unknown

Device1HasBatteryLevel=0
Device2HasBatteryLevel=1
Device3HasBatteryLevel=0
Device4HasBatteryLevel=0
Device5HasBatteryLevel=0
Device6HasBatteryLevel=0
Device7HasBatteryLevel=0
Device8HasBatteryLevel=0

Device1Battery=0
Device2Battery=90
Device3Battery=0
Device4Battery=0
Device5Battery=0
Device6Battery=0
Device7Battery=0
Device8Battery=0

Device1IsBLE=0
Device2IsBLE=1
Device3IsBLE=1
Device4IsBLE=1
Device5IsBLE=1
Device6IsBLE=1
Device7IsBLE=1
Device8IsBLE=1

Color0=255,0,0,255
Color1=0,255,0,255
