[Variables]

DevicesNumber=18

Devices=UE BOOM|56991670054|Bluetooth#Bluetootha0:29:42:3a:cd:b0-00:0d:44:f7:df:26|0|1|0|Audio/Video|Audio Video Wearable Headset|0|0|0;B06T3|171576252002104|Bluetooth#Bluetootha0:29:42:3a:cd:b0-9c:0c:35:8d:6f:38|0|1|0|Audio/Video|Audio Video Wearable Headset|0|0|0;LinkBuds S|273014288303329|Bluetooth#Bluetootha0:29:42:3a:cd:b0-f8:4e:17:ac:44:e1|0|1|0|Audio/Video|Audio Video Wearable Headset|0|0|0;Surface Slim Pen 2|234849569145700|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d5:98:2d:25:03:64|0|1|0|HumanInterfaceDevice|DigitalPen|0|0|1;Surface Arc Mouse|254394102091714|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-e7:5e:be:16:8f:c2|0|1|0|HumanInterfaceDevice|Mouse|0|0|1;NVIDIA SHIELD Remote|79921510527776|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20|0|1|0|RemoteControl|Unknown|0|0|1;MX Master 2S|223463262609936|BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-cb:3d:18:63:62:10|0|1|0|HumanInterfaceDevice|Mouse|0|0|1;

Status=1

PageDevice1=1
PageDevice2=2
PageDevice3=3
PageDevice4=4
PageDevice5=5
PageDevice6=6
PageDevice7=7
PageDevice8=8

Device1Name=UE BOOM
Device2Name=B06T3
Device3Name=LinkBuds S
Device4Name=Surface Slim Pen 2
Device5Name=Surface Arc Mouse
Device6Name=NVIDIA SHIELD Remote
Device7Name=MX Master 2S
Device8Name=Surface Slim Pen 2

Device1Address=56991670054
Device2Address=171576252002104
Device3Address=273014288303329
Device4Address=234849569145700
Device5Address=254394102091714
Device6Address=79921510527776
Device7Address=223463262609936
Device8Address=234849569145700

Device1Id=Bluetooth#Bluetootha0:29:42:3a:cd:b0-00:0d:44:f7:df:26
Device2Id=Bluetooth#Bluetootha0:29:42:3a:cd:b0-9c:0c:35:8d:6f:38
Device3Id=Bluetooth#Bluetootha0:29:42:3a:cd:b0-f8:4e:17:ac:44:e1
Device4Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d5:98:2d:25:03:64
Device5Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-e7:5e:be:16:8f:c2
Device6Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-48:b0:2d:3e:b3:20
Device7Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-cb:3d:18:63:62:10
Device8Id=BluetoothLE#BluetoothLEa0:29:42:3a:cd:b0-d5:98:2d:25:03:64

Device1Connected=0
Device2Connected=0
Device3Connected=0
Device4Connected=0
Device5Connected=0
Device6Connected=0
Device7Connected=0
Device8Connected=0

Device1Paired=1
Device2Paired=1
Device3Paired=1
Device4Paired=1
Device5Paired=1
Device6Paired=1
Device7Paired=1
Device8Paired=1

Device1CanPair=0
Device2CanPair=0
Device3CanPair=0
Device4CanPair=0
Device5CanPair=0
Device6CanPair=0
Device7CanPair=0
Device8CanPair=0

Device1MajorCategory=Audio/Video
Device2MajorCategory=Audio/Video
Device3MajorCategory=Audio/Video
Device4MajorCategory=HumanInterfaceDevice
Device5MajorCategory=HumanInterfaceDevice
Device6MajorCategory=RemoteControl
Device7MajorCategory=HumanInterfaceDevice
Device8MajorCategory=HumanInterfaceDevice

Device1MinorCategory=Audio Video Wearable Headset
Device2MinorCategory=Audio Video Wearable Headset
Device3MinorCategory=Audio Video Wearable Headset
Device4MinorCategory=DigitalPen
Device5MinorCategory=Mouse
Device6MinorCategory=Unknown
Device7MinorCategory=Mouse
Device8MinorCategory=DigitalPen

Device1HasBatteryLevel=0
Device2HasBatteryLevel=0
Device3HasBatteryLevel=0
Device4HasBatteryLevel=0
Device5HasBatteryLevel=0
Device6HasBatteryLevel=0
Device7HasBatteryLevel=0
Device8HasBatteryLevel=0

Device1Battery=0
Device2Battery=0
Device3Battery=0
Device4Battery=0
Device5Battery=0
Device6Battery=0
Device7Battery=0
Device8Battery=0

Device1IsBLE=0
Device2IsBLE=0
Device3IsBLE=0
Device4IsBLE=1
Device5IsBLE=1
Device6IsBLE=1
Device7IsBLE=1
Device8IsBLE=1

Color0=255,0,0,255
Color1=0,255,0,255
