[Variables]

DefaultFont=Droptop Roboto

;    IconStyles

;    1 = Default
;    2 = MacOS
;    3 = 8-bit
;    9 = User-defined

; -----------------------
; 1. Default

FontYposOffset1=0
FontSizeOffset1=0
IconSizeOffset1=0
TitleSpaOffset1=0

FontName10=Segoe UI

FontName11=#DefaultFont#
TopBarFontName1=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle1=1

NewDesktopStyle1=#IconStyle1#
ActionStyle1=#IconStyle1#
SearchStyle1=#IconStyle1#
TimeStyle1=#IconStyle1#
MailStyle1=#IconStyle1#
AlarmStyle1=#IconStyle1#
VolumeStyle1=#IconStyle1#
WeatherStyle1=#IconStyle1#
WifiStyle1=#IconStyle1#
BatteryStyle1=#IconStyle1#
BatteryMask1=#IconStyle1#
DownloadsStyle1=#IconStyle1#
RecentStyle1=#IconStyle1#
NotesStyle1=#IconStyle1#
CopyStyle1=#IconStyle1#
ExchangeStyle1=#IconStyle1#
LanguageStyle1=#IconStyle1#
AppDrawerStyle1=#IconStyle1#
AssistantStyle1=#IconStyle1#

DropdownSliderStyle1=1

; -----------------------
; 2. Color Match

FontYposOffset2=0
FontSizeOffset2=0
IconSizeOffset2=0
TitleSpaOffset2=0

FontName20=Segoe UI

FontName21=#DefaultFont#
TopBarFontName2=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle2=1

NewDesktopStyle2=#IconStyle2#
ActionStyle2=#IconStyle2#
SearchStyle2=#IconStyle2#
TimeStyle2=#IconStyle2#
MailStyle2=#IconStyle2#
AlarmStyle2=#IconStyle2#
VolumeStyle2=#IconStyle2#
WeatherStyle2=#IconStyle2#
WifiStyle2=#IconStyle2#
BatteryStyle2=#IconStyle2#
BatteryMask2=#IconStyle2#
DownloadsStyle2=#IconStyle2#
RecentStyle2=#IconStyle2#
NotesStyle2=#IconStyle2#
CopyStyle2=#IconStyle2#
ExchangeStyle2=#IconStyle2#
LanguageStyle2=#IconStyle2#
AppDrawerStyle2=#IconStyle2#
AssistantStyle2=#IconStyle2#

DropdownSliderStyle2=1

; -----------------------
; 3. Retro

FontYposOffset3=0
FontSizeOffset3=0
IconSizeOffset3=0
TitleSpaOffset3=0

FontName30=Pixel Cyr

FontName31=#DefaultFont#
TopBarFontName3=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle3=3

NewDesktopStyle3=#IconStyle3#
ActionStyle3=#IconStyle3#
SearchStyle3=#IconStyle3#
TimeStyle3=#IconStyle3#
MailStyle3=#IconStyle3#
AlarmStyle3=#IconStyle3#
VolumeStyle3=#IconStyle3#
WeatherStyle3=#IconStyle3#
WifiStyle3=#IconStyle3#
BatteryStyle3=#IconStyle3#
BatteryMask3=#IconStyle3#
DownloadsStyle3=#IconStyle3#
RecentStyle3=#IconStyle3#
NotesStyle3=#IconStyle3#
CopyStyle3=#IconStyle3#
ExchangeStyle3=#IconStyle3#
LanguageStyle3=#IconStyle3#
AppDrawerStyle3=#IconStyle3#
AssistantStyle3=#IconStyle3#

DropdownSliderStyle3=3

; -----------------------
; 4. Cathode

FontYposOffset4=0
FontSizeOffset4=0
IconSizeOffset4=0
TitleSpaOffset4=0

FontName40=Glass TTY VT220

FontName41=#DefaultFont#
TopBarFontName4=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle4=1

NewDesktopStyle4=#IconStyle4#
ActionStyle4=#IconStyle4#
SearchStyle4=#IconStyle4#
TimeStyle4=#IconStyle4#
MailStyle4=#IconStyle4#
AlarmStyle4=#IconStyle4#
VolumeStyle4=#IconStyle4#
WeatherStyle4=#IconStyle4#
WifiStyle4=#IconStyle4#
BatteryStyle4=#IconStyle4#
BatteryMask4=#IconStyle4#
DownloadsStyle4=#IconStyle4#
RecentStyle4=#IconStyle4#
NotesStyle4=#IconStyle4#
CopyStyle4=#IconStyle4#
ExchangeStyle4=#IconStyle4#
LanguageStyle4=#IconStyle4#
AppDrawerStyle4=#IconStyle4#
AssistantStyle4=#IconStyle4#

DropdownSliderStyle4=2

; -----------------------
; 5. Flat & Solid

FontYposOffset5=0
FontSizeOffset5=0
IconSizeOffset5=0
TitleSpaOffset5=0

FontName50=FF DIN Round Pro

FontName51=#DefaultFont#
TopBarFontName5=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle5=1

NewDesktopStyle5=#IconStyle5#
ActionStyle5=#IconStyle5#
SearchStyle5=#IconStyle5#
TimeStyle5=#IconStyle5#
MailStyle5=#IconStyle5#
AlarmStyle5=#IconStyle5#
VolumeStyle5=#IconStyle5#
WeatherStyle5=#IconStyle5#
WifiStyle5=#IconStyle5#
BatteryStyle5=#IconStyle5#
BatteryMask5=#IconStyle5#
DownloadsStyle5=#IconStyle5#
RecentStyle5=#IconStyle5#
NotesStyle5=#IconStyle5#
CopyStyle5=#IconStyle5#
ExchangeStyle5=#IconStyle5#
LanguageStyle5=#IconStyle5#
AppDrawerStyle5=#IconStyle5#
AssistantStyle5=#IconStyle5#

DropdownSliderStyle5=1

; -----------------------
; 6. Transparent

FontYposOffset6=0
FontSizeOffset6=0
IconSizeOffset6=0
TitleSpaOffset6=0

FontName60=Open Sans

FontName61=#DefaultFont#
TopBarFontName6=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle6=1

NewDesktopStyle6=#IconStyle6#
ActionStyle6=#IconStyle6#
SearchStyle6=#IconStyle6#
TimeStyle6=#IconStyle6#
MailStyle6=#IconStyle6#
AlarmStyle6=#IconStyle6#
VolumeStyle6=#IconStyle6#
WeatherStyle6=#IconStyle6#
WifiStyle6=#IconStyle6#
BatteryStyle6=#IconStyle6#
BatteryMask6=#IconStyle6#
DownloadsStyle6=#IconStyle6#
RecentStyle6=#IconStyle6#
NotesStyle6=#IconStyle6#
CopyStyle6=#IconStyle6#
ExchangeStyle6=#IconStyle6#
LanguageStyle6=#IconStyle6#
AppDrawerStyle6=#IconStyle6#
AssistantStyle6=#IconStyle6#

DropdownSliderStyle6=1

; -----------------------
; 7. Dapill

FontYposOffset7=0
FontSizeOffset7=0
IconSizeOffset7=0
TitleSpaOffset7=0

FontName70=FF DIN Round Pro

FontName71=#DefaultFont#
TopBarFontName7=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle7=1

NewDesktopStyle7=#IconStyle7#
ActionStyle7=#IconStyle7#
SearchStyle7=#IconStyle7#
TimeStyle7=#IconStyle7#
MailStyle7=#IconStyle7#
AlarmStyle7=#IconStyle7#
VolumeStyle7=#IconStyle7#
WeatherStyle7=#IconStyle7#
WifiStyle7=#IconStyle7#
BatteryStyle7=#IconStyle7#
BatteryMask7=#IconStyle7#
DownloadsStyle7=#IconStyle7#
RecentStyle7=#IconStyle7#
NotesStyle7=#IconStyle7#
CopyStyle7=#IconStyle7#
ExchangeStyle7=#IconStyle7#
LanguageStyle7=#IconStyle7#
AppDrawerStyle7=#IconStyle7#
AssistantStyle7=#IconStyle7#

DropdownSliderStyle7=1

; -----------------------
; 8. Ubuntu

FontYposOffset8=0
FontSizeOffset8=0
IconSizeOffset8=0
TitleSpaOffset8=0

FontName80=Ubuntu

FontName81=#DefaultFont#
TopBarFontName8=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle8=1

NewDesktopStyle8=#IconStyle8#
ActionStyle8=#IconStyle8#
SearchStyle8=#IconStyle8#
TimeStyle8=#IconStyle8#
MailStyle8=#IconStyle8#
AlarmStyle8=#IconStyle8#
VolumeStyle8=#IconStyle8#
WeatherStyle8=#IconStyle8#
WifiStyle8=#IconStyle8#
BatteryStyle8=#IconStyle8#
BatteryMask8=#IconStyle8#
DownloadsStyle8=#IconStyle8#
RecentStyle8=#IconStyle8#
NotesStyle8=#IconStyle8#
CopyStyle8=#IconStyle8#
ExchangeStyle8=#IconStyle8#
LanguageStyle8=#IconStyle8#
AppDrawerStyle8=#IconStyle8#
AssistantStyle8=#IconStyle8#

DropdownSliderStyle8=1

; -----------------------
; 9. Windows 95

FontYposOffset9=0
FontSizeOffset9=0
IconSizeOffset9=0
TitleSpaOffset9=0

FontName90=Microsoft Sans Serif

FontName91=#DefaultFont#
TopBarFontName9=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle9=1

NewDesktopStyle9=#IconStyle9#
ActionStyle9=#IconStyle9#
SearchStyle9=#IconStyle9#
TimeStyle9=#IconStyle9#
MailStyle9=#IconStyle9#
AlarmStyle9=#IconStyle9#
VolumeStyle9=#IconStyle9#
WeatherStyle9=#IconStyle9#
WifiStyle9=#IconStyle9#
BatteryStyle9=#IconStyle9#
BatteryMask9=#IconStyle9#
DownloadsStyle9=#IconStyle9#
RecentStyle9=#IconStyle9#
NotesStyle9=#IconStyle9#
CopyStyle9=#IconStyle9#
ExchangeStyle9=#IconStyle9#
LanguageStyle9=#IconStyle9#
AppDrawerStyle9=#IconStyle9#
AssistantStyle9=#IconStyle9#

DropdownSliderStyle9=1

; -----------------------
; 10. Catalina

FontYposOffset10=0
FontSizeOffset10=0
IconSizeOffset10=0
TitleSpaOffset10=0

FontName100=SF Pro Display

FontName101=#DefaultFont#
TopBarFontName10=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle10=2

NewDesktopStyle10=#IconStyle10#
ActionStyle10=#IconStyle10#
SearchStyle10=#IconStyle10#
TimeStyle10=#IconStyle10#
MailStyle10=#IconStyle10#
AlarmStyle10=#IconStyle10#
VolumeStyle10=#IconStyle10#
WeatherStyle10=#IconStyle10#
WifiStyle10=#IconStyle10#
BatteryStyle10=#IconStyle10#
BatteryMask10=#IconStyle10#
DownloadsStyle10=#IconStyle10#
RecentStyle10=#IconStyle10#
NotesStyle10=#IconStyle10#
CopyStyle10=#IconStyle10#
ExchangeStyle10=#IconStyle10#
LanguageStyle10=#IconStyle10#
AppDrawerStyle10=#IconStyle10#
AssistantStyle10=#IconStyle10#

DropdownSliderStyle10=2

; -----------------------
; 11. Big Sur

FontYposOffset11=0
FontSizeOffset11=0
IconSizeOffset11=0
TitleSpaOffset11=0

FontName110=SF Pro Display

FontName111=#DefaultFont#
TopBarFontName11=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle11=2

NewDesktopStyle11=#IconStyle11#
ActionStyle11=#IconStyle11#
SearchStyle11=#IconStyle11#
TimeStyle11=#IconStyle11#
MailStyle11=#IconStyle11#
AlarmStyle11=#IconStyle11#
VolumeStyle11=#IconStyle11#
WeatherStyle11=#IconStyle11#
WifiStyle11=#IconStyle11#
BatteryStyle11=#IconStyle11#
BatteryMask11=#IconStyle11#
DownloadsStyle11=#IconStyle11#
RecentStyle11=#IconStyle11#
NotesStyle11=#IconStyle11#
CopyStyle11=#IconStyle11#
ExchangeStyle11=#IconStyle11#
LanguageStyle11=#IconStyle11#
AppDrawerStyle11=#IconStyle11#
AssistantStyle11=#IconStyle11#

DropdownSliderStyle11=1

; -----------------------
; 12. Chrome OS

FontYposOffset12=0
FontSizeOffset12=0
IconSizeOffset12=0
TitleSpaOffset12=0

FontName120=Product Sans

FontName121=#DefaultFont#
TopBarFontName12=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle12=1

NewDesktopStyle12=#IconStyle12#
ActionStyle12=#IconStyle12#
SearchStyle12=#IconStyle12#
TimeStyle12=#IconStyle12#
MailStyle12=#IconStyle12#
AlarmStyle12=#IconStyle12#
VolumeStyle12=#IconStyle12#
WeatherStyle12=#IconStyle12#
WifiStyle12=#IconStyle12#
BatteryStyle12=#IconStyle12#
BatteryMask12=#IconStyle12#
DownloadsStyle12=#IconStyle12#
RecentStyle12=#IconStyle12#
NotesStyle12=#IconStyle12#
CopyStyle12=#IconStyle12#
ExchangeStyle12=#IconStyle12#
LanguageStyle12=#IconStyle12#
AppDrawerStyle12=#IconStyle12#
AssistantStyle12=#IconStyle12#

DropdownSliderStyle12=3

; -----------------------
; 13. Minimalist

FontYposOffset13=0
FontSizeOffset13=0
IconSizeOffset13=0
TitleSpaOffset13=0

FontName130=Droptop Roboto

FontName131=#DefaultFont#
TopBarFontName13=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle13=1

NewDesktopStyle13=#IconStyle13#
ActionStyle13=#IconStyle13#
SearchStyle13=#IconStyle13#
TimeStyle13=#IconStyle13#
MailStyle13=#IconStyle13#
AlarmStyle13=#IconStyle13#
VolumeStyle13=#IconStyle13#
WeatherStyle13=#IconStyle13#
WifiStyle13=#IconStyle13#
BatteryStyle13=#IconStyle13#
BatteryMask13=#IconStyle13#
DownloadsStyle13=#IconStyle13#
RecentStyle13=#IconStyle13#
NotesStyle13=#IconStyle13#
CopyStyle13=#IconStyle13#
ExchangeStyle13=#IconStyle13#
LanguageStyle13=#IconStyle13#
AppDrawerStyle13=#IconStyle13#
AssistantStyle13=#IconStyle13#

DropdownSliderStyle13=3

; -----------------------
; 14. Aperture Science

FontYposOffset14=0
FontSizeOffset14=0
IconSizeOffset14=0
TitleSpaOffset14=0

FontName140=Consolas

FontName141=#DefaultFont#
TopBarFontName14=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle14=1

NewDesktopStyle14=#IconStyle14#
ActionStyle14=#IconStyle14#
SearchStyle14=#IconStyle14#
TimeStyle14=#IconStyle14#
MailStyle14=#IconStyle14#
AlarmStyle14=#IconStyle14#
VolumeStyle14=#IconStyle14#
WeatherStyle14=#IconStyle14#
WifiStyle14=#IconStyle14#
BatteryStyle14=#IconStyle14#
BatteryMask14=#IconStyle14#
DownloadsStyle14=#IconStyle14#
RecentStyle14=#IconStyle14#
NotesStyle14=#IconStyle14#
CopyStyle14=#IconStyle14#
ExchangeStyle14=#IconStyle14#
LanguageStyle14=#IconStyle14#
AppDrawerStyle14=#IconStyle14#
AssistantStyle14=#IconStyle14#

DropdownSliderStyle14=2

; -----------------------
; 15. Windows 11

FontYposOffset15=0
FontSizeOffset15=0
IconSizeOffset15=0
TitleSpaOffset15=0

FontName150=Segoe UI

FontName151=#DefaultFont#
TopBarFontName15=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle15=1

NewDesktopStyle15=#IconStyle15#
ActionStyle15=#IconStyle15#
SearchStyle15=#IconStyle15#
TimeStyle15=#IconStyle15#
MailStyle15=#IconStyle15#
AlarmStyle15=#IconStyle15#
VolumeStyle15=#IconStyle15#
WeatherStyle15=#IconStyle15#
WifiStyle15=#IconStyle15#
BatteryStyle15=#IconStyle15#
BatteryMask15=#IconStyle15#
DownloadsStyle15=#IconStyle15#
RecentStyle15=#IconStyle15#
NotesStyle15=#IconStyle15#
CopyStyle15=#IconStyle15#
ExchangeStyle15=#IconStyle15#
LanguageStyle15=#IconStyle15#
AppDrawerStyle15=#IconStyle15#
AssistantStyle15=#IconStyle15#

DropdownSliderStyle15=2

; -----------------------
; 16. Elementary OS

FontYposOffset16=0
FontSizeOffset16=0
IconSizeOffset16=0
TitleSpaOffset16=0

FontName160=Open Sans

FontName161=#DefaultFont#
TopBarFontName16=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle16=1

NewDesktopStyle16=#IconStyle16#
ActionStyle16=#IconStyle16#
SearchStyle16=#IconStyle16#
TimeStyle16=#IconStyle16#
MailStyle16=#IconStyle16#
AlarmStyle16=#IconStyle16#
VolumeStyle16=#IconStyle16#
WeatherStyle16=#IconStyle16#
WifiStyle16=#IconStyle16#
BatteryStyle16=#IconStyle16#
BatteryMask16=#IconStyle16#
DownloadsStyle16=#IconStyle16#
RecentStyle16=#IconStyle16#
NotesStyle16=#IconStyle16#
CopyStyle16=#IconStyle16#
ExchangeStyle16=#IconStyle16#
LanguageStyle16=#IconStyle16#
AppDrawerStyle16=#IconStyle16#
AssistantStyle16=#IconStyle16#

DropdownSliderStyle16=2

; -----------------------
; 17. Tranquil

FontYposOffset17=0
FontSizeOffset17=0
IconSizeOffset17=0
TitleSpaOffset17=0

FontName170=Montserrat

FontName171=#DefaultFont#
TopBarFontName17=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle17=1

NewDesktopStyle17=#IconStyle17#
ActionStyle17=#IconStyle17#
SearchStyle17=#IconStyle17#
TimeStyle17=#IconStyle17#
MailStyle17=#IconStyle17#
AlarmStyle17=#IconStyle17#
VolumeStyle17=#IconStyle17#
WeatherStyle17=#IconStyle17#
WifiStyle17=#IconStyle17#
BatteryStyle17=#IconStyle17#
BatteryMask17=#IconStyle17#
DownloadsStyle17=#IconStyle17#
RecentStyle17=#IconStyle17#
NotesStyle17=#IconStyle17#
CopyStyle17=#IconStyle17#
ExchangeStyle17=#IconStyle17#
LanguageStyle17=#IconStyle17#
AppDrawerStyle17=#IconStyle17#
AssistantStyle17=#IconStyle17#

DropdownSliderStyle17=3

; -----------------------
; 18. Macintosh

FontYposOffset18=0
FontSizeOffset18=0
IconSizeOffset18=0
TitleSpaOffset18=0

FontName180=FA Sysfont C

FontName181=Chicago
TopBarFontName18=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle18=2

NewDesktopStyle18=#IconStyle18#
ActionStyle18=#IconStyle18#
SearchStyle18=#IconStyle18#
TimeStyle18=#IconStyle18#
MailStyle18=#IconStyle18#
AlarmStyle18=#IconStyle18#
VolumeStyle18=#IconStyle18#
WeatherStyle18=#IconStyle18#
WifiStyle18=#IconStyle18#
BatteryStyle18=#IconStyle18#
BatteryMask18=#IconStyle18#
DownloadsStyle18=#IconStyle18#
RecentStyle18=#IconStyle18#
NotesStyle18=#IconStyle18#
CopyStyle18=#IconStyle18#
ExchangeStyle18=#IconStyle18#
LanguageStyle18=#IconStyle18#
AppDrawerStyle18=#IconStyle18#
AssistantStyle18=#IconStyle18#

DropdownSliderStyle18=2

; -----------------------
; 19. Gameboy

FontYposOffset19=0
FontSizeOffset19=0
IconSizeOffset19=0
TitleSpaOffset19=0

FontName190=Diary of an 8-bit mage

FontName191=#DefaultFont#
TopBarFontName19=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle19=1

NewDesktopStyle19=#IconStyle19#
ActionStyle19=#IconStyle19#
SearchStyle19=#IconStyle19#
TimeStyle19=#IconStyle19#
MailStyle19=#IconStyle19#
AlarmStyle19=#IconStyle19#
VolumeStyle19=#IconStyle19#
WeatherStyle19=#IconStyle19#
WifiStyle19=#IconStyle19#
BatteryStyle19=#IconStyle19#
BatteryMask19=#IconStyle19#
DownloadsStyle19=#IconStyle19#
RecentStyle19=#IconStyle19#
NotesStyle19=#IconStyle19#
CopyStyle19=#IconStyle19#
ExchangeStyle19=#IconStyle19#
LanguageStyle19=#IconStyle19#
AppDrawerStyle19=#IconStyle19#
AssistantStyle19=#IconStyle19#

DropdownSliderStyle19=3

; -----------------------
; 20. Terminal

FontYposOffset20=0
FontSizeOffset20=0
IconSizeOffset20=0
TitleSpaOffset20=0

FontName200=Classic console

FontName201=#DefaultFont#
TopBarFontName20=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle20=1

NewDesktopStyle20=#IconStyle20#
ActionStyle20=#IconStyle20#
SearchStyle20=#IconStyle20#
TimeStyle20=#IconStyle20#
MailStyle20=#IconStyle20#
AlarmStyle20=#IconStyle20#
VolumeStyle20=#IconStyle20#
WeatherStyle20=#IconStyle20#
WifiStyle20=#IconStyle20#
BatteryStyle20=#IconStyle20#
BatteryMask20=#IconStyle20#
DownloadsStyle20=#IconStyle20#
RecentStyle20=#IconStyle20#
NotesStyle20=#IconStyle20#
CopyStyle20=#IconStyle20#
ExchangeStyle20=#IconStyle20#
LanguageStyle20=#IconStyle20#
AppDrawerStyle20=#IconStyle20#
AssistantStyle20=#IconStyle20#

DropdownSliderStyle20=2

; -----------------------
; 21. Senja

FontYposOffset21=0
FontSizeOffset21=0
IconSizeOffset21=0
TitleSpaOffset21=0

FontName210=Track

FontName211=#DefaultFont#
TopBarFontName21=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle21=1

NewDesktopStyle21=#IconStyle21#
ActionStyle21=#IconStyle21#
SearchStyle21=#IconStyle21#
TimeStyle21=#IconStyle21#
MailStyle21=#IconStyle21#
AlarmStyle21=#IconStyle21#
VolumeStyle21=#IconStyle21#
WeatherStyle21=#IconStyle21#
WifiStyle21=#IconStyle21#
BatteryStyle21=#IconStyle21#
BatteryMask21=#IconStyle21#
DownloadsStyle21=#IconStyle21#
RecentStyle21=#IconStyle21#
NotesStyle21=#IconStyle21#
CopyStyle21=#IconStyle21#
ExchangeStyle21=#IconStyle21#
LanguageStyle21=#IconStyle21#
AppDrawerStyle21=#IconStyle21#
AssistantStyle21=#IconStyle21#

DropdownSliderStyle21=1

; -----------------------
; 22. Discord

FontYposOffset22=0
FontSizeOffset22=0
IconSizeOffset22=0
TitleSpaOffset22=0

FontName220=Whitney

FontName221=#DefaultFont#
TopBarFontName22=[#FontName[#ThemeNum][#AltFont[#LanguageNum]]]

IconStyle22=1

NewDesktopStyle22=#IconStyle22#
ActionStyle22=#IconStyle22#
SearchStyle22=#IconStyle22#
TimeStyle22=#IconStyle22#
MailStyle22=#IconStyle22#
AlarmStyle22=#IconStyle22#
VolumeStyle22=#IconStyle22#
WeatherStyle22=#IconStyle22#
WifiStyle22=#IconStyle22#
BatteryStyle22=#IconStyle22#
BatteryMask22=#IconStyle22#
DownloadsStyle22=#IconStyle22#
RecentStyle22=#IconStyle22#
NotesStyle22=#IconStyle22#
CopyStyle22=#IconStyle22#
ExchangeStyle22=#IconStyle22#
LanguageStyle22=#IconStyle22#
AppDrawerStyle22=#IconStyle22#
AssistantStyle22=#IconStyle22#

DropdownSliderStyle22=3

; -----------------------
